export const portfolio = {
  name: "Hammad Qasim",
  role: "Creative Manager",
  agency: "Adcom Leo Burnett",
  location: "Rawalpindi, Pakistan",
  email: "hammadqasim461@gmail.com",
  statement: "Every Idea needs an insight, I'll help you find it.",
  clients: ["Ufone", "Telenor", "PTCL", "UPaisa", "e&"],
};

export const campaigns = [
  {
    id: 1,
    number: "01",
    slug: "pakistan-ki-pehchaan",
    title: "Pakistan Ki Pehchaan",
    client: "PTCL + Ufone",
    year: "2025",
    tagline: "A tribute to national identity. Built for a telecom. Earned by the nation.",
    capabilities: ["TVC", "IMC", "OOH", "Digital"],
    tvcUrl: "",
    tvcLabel: "Watch the hero TVC",
    sections: {
      context: "PTCL Group wanted to own a cultural moment: Pakistan's re-emergence on the world sports stage. Athletes like Arshad Nadeem were making history, but their journeys were going largely unrecognised. As Nation Ka Connection, PTCL and Ufone were uniquely placed to celebrate the people who gave Pakistan its pehchaan. The brief was not to run a campaign, but to build a movement.",
      insight: "Pakistan's identity has always been written in the sweat of its champions, but decades of underinvestment left those stories untold and those heroes uncelebrated. The pehchaan was never lost. It simply needed a stage.",
      idea: "Pakistan Ki Pehchaan: a storytelling platform that makes PTCL Group the enabler of national pride, not merely its sponsor. By bringing untold athlete journeys to light, the brand earns its position without making the story about itself.",
      expression: "Documentary-style films rooted in real journeys. No actors and no manufactured heroics. Real athletes, archival textures, natural light, and vernacular Urdu poetry create a visual language that feels honest. The brand remains a thread through the story, not a billboard placed over it.",
    },
    creatives: [
      { type: "Hero TVC", format: "90-second film", label: "Arshad Nadeem: From Mian Channu to the World" },
      { type: "Social Series", format: "Reels and Stories", label: "Athlete spotlight content series" },
      { type: "OOH", format: "National billboards", label: "Javelin silhouette and national identity visual language" },
      { type: "Digital KV", format: "Static and motion", label: "Pakistan Ki Pehchaan master visual" },
      { type: "Microsite", format: "Web", label: "Campaign storytelling hub" },
      { type: "Print", format: "Newspaper", label: "Independence Day campaign rollout" },
    ],
  },
  {
    id: 2,
    number: "02",
    slug: "world-animal-day",
    title: "World Animal Day",
    client: "Ufone",
    year: "2023",
    tagline: "When a telecom brand gave Pakistan's animals a voice.",
    capabilities: ["CSR", "Digital", "Social Media"],
    tvcUrl: "",
    tvcLabel: "Watch the campaign film",
    sections: {
      context: "[PLACEHOLDER] Add the original brief, campaign scale, media plan, and the specific animal-welfare challenge Ufone wanted to address for World Animal Day.",
      insight: "[PLACEHOLDER] Add the human contradiction that grounded the campaign: how people feel about pets, street animals, or wildlife versus how they behave.",
      idea: "[PLACEHOLDER] Add the central creative thought and explain how Ufone's role as a connector translated into animal welfare.",
      expression: "[PLACEHOLDER] Add the tone, visual language, social formats, and on-ground elements that made the campaign distinctly Ufone.",
    },
    creatives: [
      { type: "Social Film", format: "Digital film", label: "Campaign film details to be added" },
      { type: "Social Posts", format: "Feed carousel", label: "Visual series details to be added" },
      { type: "Activation", format: "On-ground", label: "Activation details to be added" },
    ],
  },
  {
    id: 3,
    number: "03",
    slug: "minutes-bohhaaat-hain",
    title: "Minutes Bohhaaat Hain",
    client: "Ufone",
    year: "2024",
    tagline: "A package ad that became a cultural self-portrait.",
    capabilities: ["TVC", "Digital", "Radio"],
    tvcUrl: "",
    tvcLabel: "Watch the TVC",
    sections: {
      context: "Ufone was launching UPower, a calling bundle with a huge volume of minutes at an aggressive price. Telecom advertising is usually buried in specifications, prices, and indistinguishable offer language. The challenge was to make a package advertisement people would actually remember.",
      insight: "Pakistanis are constitutionally incapable of ending a phone call on time. Aik minute never means one minute. It means a tangent about a cousin's wedding, a match recap, and a goodbye that takes three attempts. It is not a bad habit. It is one of our most recognisable cultural behaviours.",
      idea: "Lean into the truth instead of merely announcing the package. Minutes Bohhaaat Hain becomes both the product promise and an accurate description of Pakistani calling culture. Tabish Hashmi gives the behaviour a memorable face.",
      expression: "A comedy-led TVC that escalates an ordinary phone call into familiar chaos: family interruptions, dramatic asides, and the endless goodbye. The humour works as the memory device, while the offer lands naturally inside the story.",
    },
    creatives: [
      { type: "Hero TVC", format: "30 seconds", label: "Tabish Hashmi: Can't Hang Up" },
      { type: "TVC Cutdown", format: "15 seconds", label: "Offer-focused version" },
      { type: "Social Film", format: "Vertical video", label: "Social-optimised cutdown" },
      { type: "Radio", format: "30 seconds", label: "Phone-call audio gag" },
      { type: "App Banner", format: "Digital", label: "UPower package banner" },
      { type: "CRM", format: "SMS and push", label: "Subscriber activation copy" },
    ],
  },
  {
    id: 4,
    number: "04",
    slug: "super-5",
    title: "Super 5",
    client: "Ufone",
    year: "2024",
    tagline: "Pakistan's first family-sharing telecom bundle.",
    capabilities: ["TVC", "IMC", "OOH", "Digital"],
    tvcUrl: "",
    tvcLabel: "Watch the TVC",
    sections: {
      context: "Ufone launched Super 5, an unprecedented family-sharing bundle in Pakistan's telecom market. One parent number could connect four additional numbers, allowing five people to share data, minutes, and SMS. A genuinely new product needed a campaign that made the mechanics feel human.",
      insight: "Pakistani families do not simply share things. They share everything: food, cars, advice, passwords, responsibilities, and occasionally boundaries. Sharing is not a feature here. It is the operating system of family life.",
      idea: "Position Super 5 as the telecom equivalent of a Pakistani family: one plan, five people, and an endless stream of negotiations about who used what. The product does not introduce a new behaviour. It finally packages an existing one.",
      expression: "A warm comedy-led IMC campaign built around familiar family archetypes: the monitoring parent, the data-hungry teenager, and the relative who treats every shared resource as a personal entitlement. Product mechanics are explained through behaviour rather than diagrams.",
    },
    creatives: [
      { type: "Hero TVC", format: "45 seconds", label: "The family-sharing story" },
      { type: "TVC Variant", format: "30 seconds", label: "Offer mechanics version" },
      { type: "Digital KV", format: "Static and motion", label: "Super 5 master visual" },
      { type: "Social Series", format: "Short films", label: "Family vignette series" },
      { type: "OOH", format: "National rollout", label: "Super 5 outdoor campaign" },
      { type: "App Banner", format: "Digital", label: "In-app offer tile" },
    ],
  },
  {
    id: 5,
    number: "05",
    slug: "7-crore-ki-calling-family",
    title: "7 Crore Ki Calling Family",
    client: "Ufone × Telenor",
    year: "2024",
    tagline: "The biggest family reunion in Pakistan's telecom history.",
    capabilities: ["TVC", "IMC", "OOH", "Activation", "PR", "Digital"],
    tvcUrl: "",
    tvcLabel: "Watch the launch TVC",
    sections: {
      context: "The coming together of Ufone and Telenor created one of Pakistan's largest telecom moments, bringing more than 70 million customers into a shared calling ecosystem. A corporate development of enormous scale risked feeling technical, cold, and unsettling to ordinary users.",
      insight: "Mergers make headlines, but customers think about belonging. They do not ask about spectrum or corporate structure. They ask whether their family will still be connected and whether the service they trust will continue to feel familiar.",
      idea: "Reframe the network integration as the birth of Pakistan's biggest calling family: 7 crore plus people, now closer than ever. Fawad Khan and Ali Zafar appear as co-equal faces from two networks, brought together in one frame.",
      expression: "A nationwide IMC platform built on warmth, scale, and recognisable Pakistani family humour. TVC, outdoor, retail, digital, PR, and activation all present the network integration as a welcoming family reunion instead of a corporate announcement.",
    },
    creatives: [
      { type: "Hero TVC", format: "60 seconds", label: "Fawad Khan and Ali Zafar: The Reunion" },
      { type: "TVC Cutdowns", format: "30 and 15 seconds", label: "Network and offer variants" },
      { type: "OOH", format: "National rollout", label: "Dual-ambassador key visuals" },
      { type: "Campus Activation", format: "On-ground", label: "University engagement circuit" },
      { type: "PR", format: "Experiential", label: "Conversation-driving launch ideas" },
      { type: "Social", format: "Digital series", label: "7 crore stories content platform" },
      { type: "Radio", format: "Audio", label: "Launch and offer talkies" },
    ],
  },
  {
    id: 6,
    number: "06",
    slug: "regional-offer-kvs",
    title: "Regional Offer KVs",
    client: "Ufone / PTCL",
    year: "2023–2025",
    tagline: "A design system that speaks to every Pakistani region.",
    capabilities: ["Design Direction", "Visual Identity", "OOH", "Print"],
    tvcUrl: "",
    tvcLabel: "View related film",
    sections: {
      context: "Ufone and PTCL run localised offers across Pakistan with price points and benefits tailored to Punjab, Sindh, Khyber Pakhtunkhwa, Balochistan, and AJK. Generic national key visuals were being adapted for every market, reducing local relevance and in-market impact.",
      insight: "An offer in Quetta and an offer in Lahore may carry the same mechanics, but they are not the same conversation. Regional audiences respond to visual codes, language, and cultural details that acknowledge where they live.",
      idea: "Create a modular design system with consistent brand architecture and flexible regional expression. Typography, imagery, texture, and cultural cues can adapt by market while the work remains unmistakably Ufone or PTCL.",
      expression: "Region-specific visual codes sit inside a common system: folk warmth for Punjab, ajrak-inspired geometry for Sindh, bolder mountainous visual cues for Khyber Pakhtunkhwa, and textile-led earthiness for Balochistan. Local relevance without brand fragmentation.",
    },
    creatives: [
      { type: "Punjab Series", format: "Print and digital", label: "Warm palette and folk references" },
      { type: "Sindh Series", format: "Print and digital", label: "Ajrak-inspired geometric framing" },
      { type: "KPK Series", format: "Print and digital", label: "Bold graphics and mountain cues" },
      { type: "Balochistan Series", format: "Print and digital", label: "Textile texture and earthy tones" },
      { type: "Design Guide", format: "Document", label: "Regional adaptation system" },
      { type: "Retail", format: "Dealer material", label: "Franchise and shop-board templates" },
    ],
  },
  {
    id: 7,
    number: "07",
    slug: "fathers-day",
    title: "Father's Day",
    client: "Ufone + PTCL",
    year: "2024",
    tagline: "Fathers always give more.",
    capabilities: ["Film", "Digital", "Social", "Copy"],
    tvcUrl: "",
    tvcLabel: "Watch the Father's Day film",
    sections: {
      context: "Father's Day brings an annual flood of generic appreciation posts. Ufone and PTCL needed a campaign that felt specific to Pakistani fathers and emotionally honest enough to work across two brands without becoming manufactured sentiment.",
      insight: "Pakistani fathers rarely express love in grand declarations, but they show it through what they quietly give up, carry, repair, arrange, and provide. Their affection is often easiest to see in the things they do without mentioning them.",
      idea: "Fathers Always Give More: recognise fatherhood through the small, repeated acts of giving that are usually treated as ordinary. The campaign turns invisible effort into the central emotional image.",
      expression: "A restrained, human visual and copy system built around familiar gestures rather than dramatic speeches. Close observation, natural performances, and simple bilingual writing let the emotion emerge without over-explaining it.",
    },
    creatives: [
      { type: "Campaign Film", format: "Digital film", label: "Fathers Always Give More" },
      { type: "Key Visual", format: "Ufone and PTCL", label: "Dual-brand master artwork" },
      { type: "Social Posts", format: "Static and carousel", label: "Everyday acts of fatherhood" },
      { type: "OOH", format: "Billboard", label: "Campaign headline and hero image" },
      { type: "Digital Cards", format: "Shareable", label: "Father's Day greeting series" },
    ],
  },
];

export function getCampaignBySlug(slug) {
  return campaigns.find((campaign) => campaign.slug === slug) ?? null;
}
